### ISSUE TITLE
ETH support planned?

### ISSUE THREAD

**Issue by petergerten** [Peize-Liu/NxtPX4-Hardware#1]
Hi,

great project!
Any plans for a revision with ethernet mac support for fast communication with companion computer?

Peter

**Comment by Peize-Liu** [comment]
Hello,
Thank you for your advice, current version provides IMU message at 500Hz using maximum baudrate. The maximum control rate and message rate are limited by MCU frequncy and also PX4 firmware. I don't think there is a need for ethernet mac in Nxt, because of the PCB size and also the task of our research. But if there is a need for that, I may seek for some cooperation to achive that.
